import path from "node:path";
import { sql } from "drizzle-orm";
import { readMigrationFiles } from "drizzle-orm/migrator";
import { migrate } from "drizzle-orm/postgres-js/migrator";
import { db } from "./client";

// Generated by `pnpm db:generate` and copied into the image next to server.js.
const migrationsFolder = path.join(process.cwd(), "drizzle");

// Runs once at server startup, before any request is served, and logs what it
// did so the operator can see the step. Drizzle applies every migration newer
// than the last recorded one; we count those first so the log can say so.
export async function runMigrations(): Promise<void> {
  const files = readMigrationFiles({ migrationsFolder });
  const last = await lastAppliedMillis();
  const pending = files.filter((m) => last === null || last < m.folderMillis).length;

  if (pending === 0) {
    console.log(`[blastmap] migrations: nothing to apply (${files.length} known)`);
    return;
  }
  console.log(`[blastmap] migrations: applying ${pending}`);
  await migrate(db(), { migrationsFolder });
  console.log(`[blastmap] migrations: applied ${pending}`);
}

async function lastAppliedMillis(): Promise<number | null> {
  const exists = await db().execute<{ present: boolean }>(
    sql`select to_regclass('drizzle.__drizzle_migrations') is not null as present`,
  );
  if (!exists[0]?.present) return null;
  const rows = await db().execute<{ created_at: string | null }>(
    sql`select created_at from drizzle.__drizzle_migrations order by created_at desc limit 1`,
  );
  return rows[0]?.created_at ? Number(rows[0].created_at) : null;
}
